loglevel = "info"
vpn_mode = "general"
killswitch_enabled = true
killswitch_allow_ports = []
post_quantum_group_enabled = false
exclusions = []

dns_upstreams = []

[endpoint]
hostname = "watafa.duckdns.org"
addresses = ["89.124.67.54:443"]
has_ipv6 = true
username = "shwarma"
password = "Penis@1488!"
client_random = ""
skip_verification = true
certificate = ""
upstream_protocol = "http2"
upstream_fallback_protocol = ""
anti_dpi = false

[listener.tun]
bound_if = ""
included_routes = ["0.0.0.0/0", "2000::/3"]
excluded_routes = ["0.0.0.0/8", "10.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16", "224.0.0.0/3"]
mtu_size = 1500
change_system_dns = true
