name: trust_tunnel_rock
description: "TrustTunnel client"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  screen_retriever: ^0.2.0
  tray_manager: ^0.5.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

assets:
    - assets
    - assets/core/

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256

  linux:
    generate: true
    image_path: "assets/app_icon.png"
